// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: zenia/authz/admin/v1/namespace.proto

package admin

import (
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config *NamespaceConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_zenia_authz_admin_v1_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetConfig() *NamespaceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NamespaceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage *StorageConfig `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
}

func (x *NamespaceConfig) Reset() {
	*x = NamespaceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceConfig) ProtoMessage() {}

func (x *NamespaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceConfig.ProtoReflect.Descriptor instead.
func (*NamespaceConfig) Descriptor() ([]byte, []int) {
	return file_zenia_authz_admin_v1_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *NamespaceConfig) GetStorage() *StorageConfig {
	if x != nil {
		return x.Storage
	}
	return nil
}

type StorageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sharding                  *StorageConfig_Sharding `protobuf:"bytes,1,opt,name=sharding,proto3" json:"sharding,omitempty"`
	GarbageCollectionDuration *duration.Duration      `protobuf:"bytes,2,opt,name=garbage_collection_duration,json=garbageCollectionDuration,proto3" json:"garbage_collection_duration,omitempty"`
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_zenia_authz_admin_v1_namespace_proto_rawDescGZIP(), []int{2}
}

func (x *StorageConfig) GetSharding() *StorageConfig_Sharding {
	if x != nil {
		return x.Sharding
	}
	return nil
}

func (x *StorageConfig) GetGarbageCollectionDuration() *duration.Duration {
	if x != nil {
		return x.GarbageCollectionDuration
	}
	return nil
}

type StorageConfig_Sharding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// compute shard id:
	//  - objectID
	//  - relation
	//  - ...
	//
	// So that: hash(objectId) / hash(objectId, relation) / ...
	HashParameters []string `protobuf:"bytes,1,rep,name=hash_parameters,json=hashParameters,proto3" json:"hash_parameters,omitempty"`
}

func (x *StorageConfig_Sharding) Reset() {
	*x = StorageConfig_Sharding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageConfig_Sharding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig_Sharding) ProtoMessage() {}

func (x *StorageConfig_Sharding) ProtoReflect() protoreflect.Message {
	mi := &file_zenia_authz_admin_v1_namespace_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig_Sharding.ProtoReflect.Descriptor instead.
func (*StorageConfig_Sharding) Descriptor() ([]byte, []int) {
	return file_zenia_authz_admin_v1_namespace_proto_rawDescGZIP(), []int{2, 0}
}

func (x *StorageConfig_Sharding) GetHashParameters() []string {
	if x != nil {
		return x.HashParameters
	}
	return nil
}

var File_zenia_authz_admin_v1_namespace_proto protoreflect.FileDescriptor

var file_zenia_authz_admin_v1_namespace_proto_rawDesc = []byte{
	0x0a, 0x24, 0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x7a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x09,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x50, 0x0a, 0x0f,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x3d, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0xe9,
	0x01, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x48, 0x0a, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x59, 0x0a, 0x1b, 0x67, 0x61,
	0x72, 0x62, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x19, 0x67, 0x61, 0x72, 0x62,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x33, 0x0a, 0x08, 0x53, 0x68, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x27, 0x0a, 0x0f, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x68,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x62, 0x69, 0x6e, 0x62, 0x72,
	0x61, 0x65, 0x6d, 0x65, 0x72, 0x2f, 0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x7a, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_zenia_authz_admin_v1_namespace_proto_rawDescOnce sync.Once
	file_zenia_authz_admin_v1_namespace_proto_rawDescData = file_zenia_authz_admin_v1_namespace_proto_rawDesc
)

func file_zenia_authz_admin_v1_namespace_proto_rawDescGZIP() []byte {
	file_zenia_authz_admin_v1_namespace_proto_rawDescOnce.Do(func() {
		file_zenia_authz_admin_v1_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(file_zenia_authz_admin_v1_namespace_proto_rawDescData)
	})
	return file_zenia_authz_admin_v1_namespace_proto_rawDescData
}

var file_zenia_authz_admin_v1_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zenia_authz_admin_v1_namespace_proto_goTypes = []interface{}{
	(*Namespace)(nil),              // 0: zenia.authz.admin.v1.Namespace
	(*NamespaceConfig)(nil),        // 1: zenia.authz.admin.v1.NamespaceConfig
	(*StorageConfig)(nil),          // 2: zenia.authz.admin.v1.StorageConfig
	(*StorageConfig_Sharding)(nil), // 3: zenia.authz.admin.v1.StorageConfig.Sharding
	(*duration.Duration)(nil),      // 4: google.protobuf.Duration
}
var file_zenia_authz_admin_v1_namespace_proto_depIdxs = []int32{
	1, // 0: zenia.authz.admin.v1.Namespace.config:type_name -> zenia.authz.admin.v1.NamespaceConfig
	2, // 1: zenia.authz.admin.v1.NamespaceConfig.storage:type_name -> zenia.authz.admin.v1.StorageConfig
	3, // 2: zenia.authz.admin.v1.StorageConfig.sharding:type_name -> zenia.authz.admin.v1.StorageConfig.Sharding
	4, // 3: zenia.authz.admin.v1.StorageConfig.garbage_collection_duration:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_zenia_authz_admin_v1_namespace_proto_init() }
func file_zenia_authz_admin_v1_namespace_proto_init() {
	if File_zenia_authz_admin_v1_namespace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zenia_authz_admin_v1_namespace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zenia_authz_admin_v1_namespace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zenia_authz_admin_v1_namespace_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zenia_authz_admin_v1_namespace_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageConfig_Sharding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zenia_authz_admin_v1_namespace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zenia_authz_admin_v1_namespace_proto_goTypes,
		DependencyIndexes: file_zenia_authz_admin_v1_namespace_proto_depIdxs,
		MessageInfos:      file_zenia_authz_admin_v1_namespace_proto_msgTypes,
	}.Build()
	File_zenia_authz_admin_v1_namespace_proto = out.File
	file_zenia_authz_admin_v1_namespace_proto_rawDesc = nil
	file_zenia_authz_admin_v1_namespace_proto_goTypes = nil
	file_zenia_authz_admin_v1_namespace_proto_depIdxs = nil
}
